In [1]:
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
import os

data=pd.read_csv("date_data/2022-07-01.csv")
display(data.head())

,時間,ソアリン,トイストーリーマニア,タワーオブテラー,センターオブジアース,インディージョーンズ,レイジングスピリッツ,マジックランプシアター,タートルトーク
0,2022-07-01 09:00:00,95,65,50,25,5,5,0,0
1,2022-07-01 09:15:00,80,65,45,35,10,5,0,0
2,2022-07-01 09:30:00,110,65,55,45,10,10,0,0
3,2022-07-01 09:45:00,110,65,60,45,10,10,0,0
4,2022-07-01 10:00:00,120,65,55,40,20,20,30,15

In [2]:
data['時間'] = pd.to_datetime(data['時間'] )
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   時間           48 non-null     datetime64[ns]
 1   ソアリン         48 non-null     int64
 2   トイストーリーマニア   48 non-null     int64
 3   タワーオブテラー     48 non-null     int64
 4   センターオブジアース   48 non-null     int64
 5   インディージョーンズ   48 non-null     int64
 6   レイジングスピリッツ   48 non-null     int64
 7   マジックランプシアター  48 non-null     int64
 8   タートルトーク      48 non-null     int64
dtypes: datetime64[ns](1), int64(8)
memory usage: 3.5 KB
None

In [3]:
data=data.set_index('時間')
display(data.head())

,ソアリン,トイストーリーマニア,タワーオブテラー,センターオブジアース,インディージョーンズ,レイジングスピリッツ,マジックランプシアター,タートルトーク
時間,,,,,,,,
2022-07-01 09:00:00,95,65,50,25,5,5,0,0
2022-07-01 09:15:00,80,65,45,35,10,5,0,0
2022-07-01 09:30:00,110,65,55,45,10,10,0,0
2022-07-01 09:45:00,110,65,60,45,10,10,0,0
2022-07-01 10:00:00,120,65,55,40,20,20,30,15

In [4]:
# 行数を指定すると所用時間を返す関数
def knapsack(row_x, data_x,required_time_x, waiting_time_x, move_time_x, attraction_no_x):
    waiting_time_x = data_x.iloc[row_x, attraction_no_x]
    ans = required_time_x + waiting_time_x + move_time_x
    return ans

In [5]:
# アトラクションの所要時間と人気度
attractions = ['ソアリン', 'トイストーリーマニア', 'タワーオブテラー', 'センターオブジアース', 'インディージョーンズ', 'レイジングスピリッツ', 'マジックランプシアター', 'タートルトーク']
required_times = [5, 7, 2, 3, 3, 2, 23, 30]
popularity = [84, 69, 55, 45, 33, 28, 19, 22]
max_time = 60  # パーク内にいる時間 9:00~20:45 計705分

In [6]:
#start_time = datetime.strptime(data.index[0], '%Y-%m-%d %H:%M:%S')
start_time = data.index[0]
print("start time is:",start_time)

row=0
#インディジョーンズにのる場合
#9:00の時点で5分まち
waiting_time = data.iloc[0,4]
print("Waiting time is:", waiting_time)
#3分
required_time = required_times[4]
print("Required time is:", required_time)

#5+3+30=38分
ans=knapsack(row, data,required_time, waiting_time, 30, 4)
print("Necesary time is:",ans)

start time is: 2022-07-01 09:00:00
Waiting time is: 5
Required time is: 3
Necesary time is: 38

In [7]:
#次に考える行の番号
next_row=np.ceil(ans/15)
print(next_row)

3.0

In [55]:
#行番号3、つまり9:45が次のスタートライン。