In [358]:
# 分を24時間表示に変換
def calculate_time(minutes):
    # 9:00 を0分、20:00 を660分として計算
    start_time = 9 * 60  # 9:00を分単位に変換
    end_time = 20 * 60  # 20:00を分単位に変換
    
    total_minutes = start_time + minutes
    
    # 時間と分に変換
    hours = total_minutes // 60
    mins = total_minutes % 60
    
    # 24時間表記に変換
    if hours >= 24:
        hours -= 24
    
    # 時間と分を文字列に変換して返す
    return f"{hours:02d}:{mins:02d}"

In [359]:
# 24時間表示を分に変換
def calculate_minutes(time_str):
    # 時刻を時間と分に分割
    hours, mins = map(int, time_str.split(":"))
    
    # 9:00 を0分、20:00 を660分として計算
    start_time = 9 * 60  # 9:00を分単位に変換
    end_time = 20 * 60  # 20:00を分単位に変換
    
    # 入力された時刻を分単位に変換
    total_minutes = hours * 60 + mins
    
    # 24時間以上の場合は調整
    if total_minutes < start_time:
        total_minutes += 24 * 60
    
    # 開始時刻からの経過時間を計算
    elapsed_minutes = total_minutes - start_time
    
    return elapsed_minutes

In [419]:
def not_in_new_ride(a, b):
    ans=a
    # リストaからリストbに含まれている要素を取り除く
    for item in b:
        if item in a:
            ans.remove(item)
    return ans

In [420]:
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
import os
import math

data=pd.read_csv("date_data2/2022-07-01.csv")
display(data.head())

data=data.set_index('時間')
display(data.head())

,時間,ソアリン,トイストーリーマニア,タワーオブテラー,センターオブジアース,インディージョーンズ,レイジングスピリッツ,マジックランプシアター,タートルトーク
0,0,95,65,50,25,5,5,0,0
1,15,80,65,45,35,10,5,0,0
2,30,110,65,55,45,10,10,0,0
3,45,110,65,60,45,10,10,0,0
4,60,120,65,55,40,20,20,30,15

,ソアリン,トイストーリーマニア,タワーオブテラー,センターオブジアース,インディージョーンズ,レイジングスピリッツ,マジックランプシアター,タートルトーク
時間,,,,,,,,
0,95,65,50,25,5,5,0,0
15,80,65,45,35,10,5,0,0
30,110,65,55,45,10,10,0,0
45,110,65,60,45,10,10,0,0
60,120,65,55,40,20,20,30,15

In [421]:
# 行数を指定すると所用時間を返す関数
def knapsack(row_x, data_x,required_time_x, waiting_time_x, move_time_x, attraction_no_x):
    waiting_time_x = data_x.iloc[row_x, attraction_no_x]
    ans = required_time_x + waiting_time_x + move_time_x
    return ans

In [422]:
# アトラクションの所要時間と人気度
attractions = {
    0 : 'ソアリン',
    1 : 'トイストーリーマニア',
    2 : 'タワーオブテラー',
    3 : 'センターオブジアース',
    4 : 'インディージョーンズ',
    5 : 'レイジングスピリッツ',
    6 : 'マジックランプシアター',
    7 : 'タートルトーク'
}
required_times = [5, 7, 2, 3, 3, 2, 23, 30] # 所要時間
popularity = [84, 69, 55, 45, 33, 28, 19, 22] #人気度
max_time = 60  # パーク内にいる時間 9:00~20:00 計660分 (20時以降はファストパスのみ受け入れと仮定)
move_time = 10

In [442]:
# 合計所要時間と合計人気度を算出する関数
def ride_calculation(data, ride_lst, required_times, move_time):
    total_popularity = 0
    total_time = 0
    ride_time = []
    new_ride_lst = []
    # start_time = data.index[0]
    # print("start time is:", calculate_time(start_time))
    row = 0
    try:
        for i in ride_lst:
            # total_timeが675以上かつiが0または1の場合にループを強制終了
            # ソアリン、トイストーリーMは20:15以降DPA所持者のみ乗車可能
            if (data.index[row]) >= 675 and (i == 0 or i == 1):
                continue
            
            else:
                # iが8以上の場合、次のループへ(該当しないアトラクション)
                if i >= 8 or i < 0:
                    # print("不明なアトラクション：", i)
                    continue
                else:
                    # print("-" * 40)
                    print(calculate_time(data.index[row]))
                    ride_time.append(data.index[row])
                    print(attractions.get(i))
                    # print("移動時間", move_time)
                    waiting_time = data.iloc[row, i]
                    # print("待ち時間:", waiting_time)
                    required_time = required_times[i]
                    # print("観賞時間:", required_time)
                    ans = knapsack(row, data, required_time, waiting_time, move_time, i)
                    # print("合計所要時間:", ans)
                    total_time += ans
                    row = int(np.ceil(total_time / 15))
                    total_popularity += popularity[i]
                    new_ride_lst.append(i)
    except Exception as e:
        # print("全てのアトラクションを乗ることができません")
        pass

    # print("-" * 40)
    return total_popularity, total_time, new_ride_lst, ride_time

In [443]:
def ride_printer(total_popularity, total_time, ride_lst, new_ride_lst, ride_time):
    print("-" * 40)
    print("乗車プラン")
    for i in range(len(new_ride_lst)):
        print(f"{calculate_time(ride_time[i])}　： {attractions.get(new_ride_lst[i])}")
    print('トータル所要時間：',total_time)
    print('トータル満足度　：',total_popularity)
    print("-" * 40)
    if not(len(ride_lst)==len(new_ride_lst)):
        print("※全てのアトラクションを乗ることができません")
        print("プランに除外されたアトラクション")
        not_ride = not_in_new_ride(ride_lst, new_ride_lst)
        for i in not_ride:
            print(f"{i}　： {attractions.get(i)}")

In [447]:
ride_lst=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]

total_popularity, total_time, new_ride_lst, ride_time = ride_calculation(data, ride_lst, required_times, move_time)

ride_printer(total_popularity, total_time, ride_lst, new_ride_lst, ride_time)

09:00
ソアリン
11:00
ソアリン
12:15
ソアリン
13:00
ソアリン
14:30
ソアリン
15:45
ソアリン
16:45
ソアリン
17:45
ソアリン
18:45
ソアリン
20:00
ソアリン
----------------------------------------
乗車プラン
09:00　： ソアリン
11:00　： ソアリン
12:15　： ソアリン
13:00　： ソアリン
14:30　： ソアリン
15:45　： ソアリン
16:45　： ソアリン
17:45　： ソアリン
18:45　： ソアリン
20:00　： ソアリン
トータル所要時間： 735
トータル満足度　： 840
----------------------------------------
※全てのアトラクションを乗ることができません
プランに除外されたアトラクション
0　： ソアリン
0　： ソアリン
0　： ソアリン
0　： ソアリン
0　： ソアリン
0　： ソアリン
0　： ソアリン
0　： ソアリン
0　： ソアリン
0　： ソアリン
0　： ソアリン
0　： ソアリン
0　： ソアリン
0　： ソアリン

In [438]:
print(calculate_minutes("20:15"))

675